algoritmo "semnome"
// Função :
// Autor :
// Data : 23/02/2026
// Seção de Declarações 
var
op: literal
inicio
// Seção de Comandos 
repita
escreval("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~")
escreval("|qual das opçoes abaixo vc prefere|")
escreval("|        1- gravity falls         |")
escreval("|        2-casa coruja            |")
escreval("|        3-doctor who             |")
escreval("|        4-sair do p              |")
escreval("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~")
leia(op)
escolha op
caso "1"
escreval("bom gosto")
caso "2"
escreval("bem gay e muito bom")
caso "3"
escreval("muitooooooooooo bommm ")
fimescolha
ate op="4"
fimrepita
fimalgoritmo
