algoritmo "semnome"

var
num1, num2: inteiro
soma, sub, divisao, multi: real
inicio
escreva("Digite um número: ")
leia(num1)
escreva("Digite outro número:")
leia(num2)

soma <- num1+num2
sub <- num1-num2
divisao <- num1/num2
multi <- num1*num2

escreval("A soma dos valores é:", soma)
escreval("A subtração dos valores é:", sub)
escreval("A multiplicação dos valores é:", multi)
escreval("A divisão dos valores é:", divisao)
fimalgoritmo
