algoritmo "semnome"

// Função :

// Autor :

// Data : 27/02/2026

// Seção de Declarações

var

      x: real

      i: real

      op:inteiro

      soma: real

      sub:real

      mut:real

      divo:real

inicio

// Seção de Comandos

op <- 1

enquanto op<>0 faca

escreval("------------------------------")
escreval("|          multimetro-foda    | ")
escreval("|          1-chuveiro         |")
escreval("|           2- tomada         |")
escreval("|           3-treco           |")
escreval("|           4-braga           |")
escreval("|         0-encerrar          |")
escreval("------------------------------")

leia(op)

escolha op

caso 1

   escreval("chuveiro vai queiamr esta con 200 paranaue ")


caso 2
    escreval("tomada de 120  volts")
caso 3


    escreval("o treci esta com tensao eletrica de 200 volts")

caso 4


    escreval("assarm o loroooooooooo ")


fimescolha



fimenquanto

fimalgoritmo
