algoritmo "semnome"
// Função :
// Autor :
// Data : 27/02/2026
// Seção de Declarações
var
op: real

procedimento ops


inicio
escreval("------------------------")
escreval("|      1-casa coruja    |")
escreval("|      2-gravity fals   |")
escreval("|      3-nao sei        |")
escreval("|      4-fechar         |")
escreval("-------------------------")
leia(op)
fimprocedimento
inicio
// Seção de Comandos
repita
ops()
escolha op
caso 1
   escreval("muito bom e fofo")
caso 2
   escreval("bommmm")
caso 3
   escreval("sei la")

fimescolha


ate op=4
fimalgoritmo
