algoritmo "tabuada"

// Função :

// Autor :

// Data : 27/02/2026

// Seção de Declarações

var      i:real

       op: real

       cont:real

       x:real

       resultado: real



inicio

// Seção de Comandos

  escreval("qual numero voce quer mutiplicar ")

  leia(x)

  escreval("ate que numero")

  leia(i)

  cont<- 0
  i<- i+1

enquanto cont<i faca









  resultado<- x *cont

  escreval(resultado)

    cont<- cont+1
    
    
    fimenquanto
    fimalgoritmo
